export function validateEmail(e){return/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(e)}function getFeedbackIcon(e){return"success"===e?`
      <span class="feedback-icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
          <path fill="currentColor" d="M512 64a448 448 0 1 1 0 896a448 448 0 0 1 
            0-896m-55.808 536.384l-99.52-99.584a38.4 38.4 0 1 0-54.336 54.336l126.72 126.72a38.27 38.27 0 0 0 54.336 0l262.4-262.464a38.4 38.4 0 1 0-54.272-54.336z"/>
        </svg>
      </span>`:`
      <span class="feedback-icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
          <path fill="currentColor" d="M12.884 2.532c-.346-.654-1.422-.654-1.768 0l-9 17A1 
            1 0 0 0 3 21h18a.998.998 0 0 0 .883-1.467zM13 18h-2v-2h2zm-2-4V9h2l.001 5z"/>
        </svg>
      </span>`}function showFeedback(e,r="success"){let s=document.getElementById("feedback-email"),t=document.getElementById("feedback-icon"),a=document.getElementById("feedback-text");s&&t&&a&&(s.classList.remove("error","success"),t.innerHTML=getFeedbackIcon(r),a.textContent=e,s.classList.add(r))}function clearFeedback(){let e=document.getElementById("feedback-email"),r=document.getElementById("feedback-icon"),s=document.getElementById("feedback-text");e&&r&&s&&(e.classList.remove("error","success"),r.innerHTML="",s.textContent="")}export function handleNewsletterForm(e){if(!e)return;let r=e.querySelector("input[type='email']"),s=e.querySelector("button[type='submit']");r&&s&&(r.addEventListener("input",()=>{let e=r.value.trim();if(r.classList.remove("error-border","success-border"),!e){clearFeedback();return}validateEmail(e)?(r.classList.add("success-border"),showFeedback("Correcto","success")):(r.classList.add("error-border"),showFeedback("Email inv\xe1lido","error"))}),r.addEventListener("blur",()=>{let e=r.value.trim();e?validateEmail(e)||(r.classList.add("error-border"),showFeedback("Email inv\xe1lido.","error")):(r.classList.add("error-border"),showFeedback("El campo de email no puede estar vac\xedo","error"))}),e.addEventListener("submit",async function(t){t.preventDefault();let a=r.value.trim();if(clearFeedback(),r.classList.remove("error-border","success-border"),!validateEmail(a)){r.classList.add("error-border"),showFeedback("Por favor ingrese un email v\xe1lido","error");return}if(s.disabled)return;s.disabled=!0;let o=s.textContent;s.textContent="Enviando...";try{let c=new FormData(e),d=await fetch("https://api.web3forms.com/submit",{method:"POST",body:c}),i=await d.json();d.ok&&i.success?(showFeedback("Gracias por suscribirte","success"),e.reset(),r.classList.remove("error-border"),r.classList.add("success-border")):(showFeedback(i.message||"Error al enviar el formulario.","error"),r.classList.add("error-border"))}catch(l){showFeedback("Error de red. Intenta nuevamente.","error"),r.classList.add("error-border")}finally{s.disabled=!1,s.textContent=o,setTimeout(()=>{clearFeedback(),r.classList.remove("success-border","error-border")},3e3)}}))}